version: "3.9"

services:
  db:
    image: postgres:15
    container_name: quiz-postgres
    environment:
      POSTGRES_DB: assignment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - quiz_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d quizdb"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quiz-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://db:5432/assignment
      DB_USERNAME: postgres
      DB_PASSWORD: root
      JAVA_OPTS: -XX:MaxRAMPercentage=75.0
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  quiz_pg_data:
